### ISSUE TITLE
TypeError: Invalid comparison between dtype=datetime64[ns] and date

### ISSUE THREAD

**Issue by charifbahloul** [TimRivoli/Stock-Price-Trade-Analyzer#3]
Hi.
Whenever I come to run any one of the programs, the following error comes up.

In [1]: runfile('C:/Users/*name*/Desktop/Stock-Price-Trade-Analyzer-master/Stock-Price-Trade-Analyzer-master/EvaluatePrices.py', wdir='C:/Users/*name*/Desktop/Stock-Price-Trade-Analyzer-master/Stock-Price-Trade-Analyzer-master')
Loading ^SPX
Calcualting stats ^SPX
Graphing ^SPX 2021-01-19
Saved to data/charts/^SPX_0090d.png
Saved to data/charts/^SPX_0180d.png
Saved to data/charts/^SPX_0365d.png
Saved to data/charts/^SPX_2190d.png
Saved to data/charts/^SPX_4380d.png
Loading ^DJI
Calcualting stats ^DJI
Graphing ^DJI 2021-01-19
Saved to data/charts/^DJI_0090d.png
Saved to data/charts/^DJI_0180d.png
Saved to data/charts/^DJI_0365d.png
Saved to data/charts/^DJI_2190d.png
Saved to data/charts/^DJI_4380d.png
Loading ^NDQ
Calcualting stats ^NDQ
Graphing ^NDQ 2021-01-19
Saved to data/charts/^NDQ_0090d.png
Saved to data/charts/^NDQ_0180d.png
Saved to data/charts/^NDQ_0365d.png
Saved to data/charts/^NDQ_2190d.png
Saved to data/charts/^NDQ_4380d.png
Loading AAPL
Traceback (most recent call last):

File "C:\Users\*name*\AppData\Local\Programs\Spyder\Python\lib\site-packages\pandas\core\arrays\datetimelike.py", line 116, in wrapper
other = _validate_comparison_value(self, other)

File "C:\Users\*name*\AppData\Local\Programs\Spyder\Python\lib\site-packages\pandas\core\arrays\datetimelike.py", line 96, in _validate_comparison_value
raise InvalidComparison(other)

InvalidComparison: 2019-12-07

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

File "C:\Users\*name*\Desktop\Stock-Price-Trade-Analyzer-master\Stock-Price-Trade-Analyzer-master\EvaluatePrices.py", line 143, in <module>
CalculatePriceCorrelation(TickerLists.SPTop70())

File "C:\Users\*name*\Desktop\Stock-Price-Trade-Analyzer-master\Stock-Price-Trade-Analyzer-master\EvaluatePrices.py", line 74, in CalculatePriceCorrelation
prices.TrimToDateRange(startDate, endDate)

File "C:\Users\*name*\Desktop\Stock-Price-Trade-Analyzer-master\Stock-Price-Trade-Analyzer-master\_classes\PriceTradeAnalyzer.py", line 295, in TrimToDateRange
self.historicalPrices = self.historicalPrices[(self.historicalPrices.index >= startDate) & (self.historicalPrices.index <= endDate)]

File "C:\Users\*name*\AppData\Local\Programs\Spyder\Python\lib\site-packages\pandas\core\indexes\extension.py", line 129, in wrapper
return op(other)

File "C:\Users\*name*\AppData\Local\Programs\Spyder\Python\lib\site-packages\pandas\core\ops\common.py", line 65, in new_method
return method(self, other)

File "C:\Users\*name*\AppData\Local\Programs\Spyder\Python\lib\site-packages\pandas\core\arrays\datetimelike.py", line 118, in wrapper
return invalid_comparison(self, other, op)

File "C:\Users\*name*\AppData\Local\Programs\Spyder\Python\lib\site-packages\pandas\core\ops\invalid.py", line 34, in invalid_comparison
raise TypeError(f"Invalid comparison between dtype={left.dtype} and {typ}")

TypeError: Invalid comparison between dtype=datetime64[ns] and date

In [2]: runfile('C:/Users/*name*/Desktop/Stock-Price-Trade-Analyzer-master/Stock-Price-Trade-Analyzer-master/EvaluateTradeModels.py', wdir='C:/Users/*name*/Desktop/Stock-Price-Trade-Analyzer-master/Stock-Price-Trade-Analyzer-master')
Running model BuyAndHold_BAC
Traceback (most recent call last):

File "C:\Users\*name*\AppData\Local\Programs\Spyder\Python\lib\site-packages\pandas\core\arrays\datetimelike.py", line 116, in wrapper
other = _validate_comparison_value(self, other)

File "C:\Users\*name*\AppData\Local\Programs\Spyder\Python\lib\site-packages\pandas\core\arrays\datetimelike.py", line 96, in _validate_comparison_value
raise InvalidComparison(other)

InvalidComparison: 1986-11-17

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

File "C:\Users\*name*\Desktop\Stock-Price-Trade-Analyzer-master\Stock-Price-Trade-Analyzer-master\EvaluateTradeModels.py", line 286, in <module>
RunModel('BuyAndHold', RunTradingModelBuyHold, 'BAC','1/1/1987', 30, 30000, verbose=False)

File "C:\Users\*name*\Desktop\Stock-Price-Trade-Analyzer-master\Stock-Price-Trade-Analyzer-master\EvaluateTradeModels.py", line 30, in RunModel
tm = TradingModel(modelName=modelName, startingTicker=ticker, startDate=startDate, durationInYears=durationInYears, totalFunds=portfolioSize, tranchSize=round(portfolioSize/10), verbose=verbose)

File "C:\Users\*name*\Desktop\Stock-Price-Trade-Analyzer-master\Stock-Price-Trade-Analyzer-master\_classes\PriceTradeAnalyzer.py", line 1215, in __init__
if p.LoadHistory(requestedStartDate=startDate, requestedEndDate=endDate, verbose=verbose):

File "C:\Users\*name*\Desktop\Stock-Price-Trade-Analyzer-master\Stock-Price-Trade-Analyzer-master\_classes\PriceTradeAnalyzer.py", line 288, in LoadHistory
self.TrimToDateRange(requestedStartDate, requestedEndDate)

File "C:\Users\*name*\Desktop\Stock-Price-Trade-Analyzer-master\Stock-Price-Trade-Analyzer-master\_classes\PriceTradeAnalyzer.py", line 295, in TrimToDateRange
self.historicalPrices = self.historicalPrices[(self.historicalPrices.index >= startDate) & (self.historicalPrices.index <= endDate)]

File "C:\Users\*name*\AppData\Local\Programs\Spyder\Python\lib\site-packages\pandas\core\indexes\extension.py", line 129, in wrapper
return op(other)

File "C:\Users\*name*\AppData\Local\Programs\Spyder\Python\lib\site-packages\pandas\core\ops\common.py", line 65, in new_method
return method(self, other)

File "C:\Users\*name*\AppData\Local\Programs\Spyder\Python\lib\site-packages\pandas\core\arrays\datetimelike.py", line 118, in wrapper
return invalid_comparison(self, other, op)

File "C:\Users\*name*\AppData\Local\Programs\Spyder\Python\lib\site-packages\pandas\core\ops\invalid.py", line 34, in invalid_comparison
raise TypeError(f"Invalid comparison between dtype={left.dtype} and {typ}")

TypeError: Invalid comparison between dtype=datetime64[ns] and date

In [3]: runfile('C:/Users/*name*/Desktop/Stock-Price-Trade-Analyzer-master/Stock-Price-Trade-Analyzer-master/TrainPrices.py', wdir='C:/Users/*name*/Desktop/Stock-Price-Trade-Analyzer-master/Stock-Price-Trade-Analyzer-master')

2021-01-20 13:45:10.472274: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2021-01-20 13:45:10.472451: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Loading BAC
Traceback (most recent call last):

File "C:\Users\*name*\AppData\Local\Programs\Spyder\Python\lib\site-packages\pandas\core\arrays\datetimelike.py", line 116, in wrapper
other = _validate_comparison_value(self, other)

File "C:\Users\*name*\AppData\Local\Programs\Spyder\Python\lib\site-packages\pandas\core\arrays\datetimelike.py", line 96, in _validate_comparison_value
raise InvalidComparison(other)

InvalidComparison: 1999-11-17

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

File "C:\Users\*name*\Desktop\Stock-Price-Trade-Analyzer-master\Stock-Price-Trade-Analyzer-master\TrainPrices.py", line 83, in <module>
TrainTickerRaw('BAC', UseLSTM=False, useGenericModel=False, prediction_target_days = 5, epochs = 400)

File "C:\Users\*name*\Desktop\Stock-Price-Trade-Analyzer-master\Stock-Price-Trade-Analyzer-master\TrainPrices.py", line 32, in TrainTickerRaw
prices.TrimToDateRange('1/1/2000', '3/1/2018')

File "C:\Users\*name*\Desktop\Stock-Price-Trade-Analyzer-master\Stock-Price-Trade-Analyzer-master\_classes\PriceTradeAnalyzer.py", line 295, in TrimToDateRange
self.historicalPrices = self.historicalPrices[(self.historicalPrices.index >= startDate) & (self.historicalPrices.index <= endDate)]

File "C:\Users\*name*\AppData\Local\Programs\Spyder\Python\lib\site-packages\pandas\core\indexes\extension.py", line 129, in wrapper
return op(other)

File "C:\Users\*name*\AppData\Local\Programs\Spyder\Python\lib\site-packages\pandas\core\ops\common.py", line 65, in new_method
return method(self, other)

File "C:\Users\*name*\AppData\Local\Programs\Spyder\Python\lib\site-packages\pandas\core\arrays\datetimelike.py", line 118, in wrapper
return invalid_comparison(self, other, op)

File "C:\Users\*name*\AppData\Local\Programs\Spyder\Python\lib\site-packages\pandas\core\ops\invalid.py", line 34, in invalid_comparison
raise TypeError(f"Invalid comparison between dtype={left.dtype} and {typ}")

TypeError: Invalid comparison between dtype=datetime64[ns] and date

In [4]: runfile('C:/Users/*name*/Desktop/Stock-Price-Trade-Analyzer-master/Stock-Price-Trade-Analyzer-master/PredictionExperiment.py', wdir='C:/Users/*name*/Desktop/Stock-Price-Trade-Analyzer-master/Stock-Price-Trade-Analyzer-master')
Loading ^SPX
Loading ^SPX
experiment/samples\LSTMsampleLearning 2020-03-24 00:00:00 2020-12-29 00:00:00 2021-01-19 00:00:00
Loading ^SPX
experiment/samples\CNNsampleLearning 2017-09-05 00:00:00 2020-09-29 00:00:00 2021-01-19 00:00:00
2017-09-05 00:00:00 2017-09-19 00:00:00 80 10
2017-12-26 00:00:00 2018-01-09 00:00:00 80 10
2018-04-17 00:00:00 2018-05-01 00:00:00 80 10
2018-08-07 00:00:00 2018-08-21 00:00:00 80 10
2018-11-27 00:00:00 2018-12-11 00:00:00 80 10
2019-03-19 00:00:00 2019-04-02 00:00:00 80 10
2019-07-09 00:00:00 2019-07-23 00:00:00 80 10
2019-10-29 00:00:00 2019-11-12 00:00:00 80 10
2020-02-18 00:00:00 2020-03-03 00:00:00 80 10
2020-06-09 00:00:00 2020-06-23 00:00:00 80 10
Sample data has been placed in experiment/
Loading NFLX
Traceback (most recent call last):

File "C:\Users\*name*\AppData\Local\Programs\Spyder\Python\lib\site-packages\pandas\core\arrays\datetimelike.py", line 116, in wrapper
other = _validate_comparison_value(self, other)

File "C:\Users\*name*\AppData\Local\Programs\Spyder\Python\lib\site-packages\pandas\core\arrays\datetimelike.py", line 96, in _validate_comparison_value
raise InvalidComparison(other)

InvalidComparison: 1949-11-17

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

File "C:\Users\*name*\Desktop\Stock-Price-Trade-Analyzer-master\Stock-Price-Trade-Analyzer-master\PredictionExperiment.py", line 147, in <module>
RunPredictions(StockTicker, numberOfLearningPasses=450)

File "C:\Users\*name*\Desktop\Stock-Price-Trade-Analyzer-master\Stock-Price-Trade-Analyzer-master\PredictionExperiment.py", line 122, in RunPredictions
prices.TrimToDateRange('1/1/1950', '3/1/2018')

File "C:\Users\*name*\Desktop\Stock-Price-Trade-Analyzer-master\Stock-Price-Trade-Analyzer-master\_classes\PriceTradeAnalyzer.py", line 295, in TrimToDateRange
self.historicalPrices = self.historicalPrices[(self.historicalPrices.index >= startDate) & (self.historicalPrices.index <= endDate)]

File "C:\Users\*name*\AppData\Local\Programs\Spyder\Python\lib\site-packages\pandas\core\indexes\extension.py", line 129, in wrapper
return op(other)

File "C:\Users\*name*\AppData\Local\Programs\Spyder\Python\lib\site-packages\pandas\core\ops\common.py", line 65, in new_method
return method(self, other)

File "C:\Users\*name*\AppData\Local\Programs\Spyder\Python\lib\site-packages\pandas\core\arrays\datetimelike.py", line 118, in wrapper
return invalid_comparison(self, other, op)

File "C:\Users\*name*\AppData\Local\Programs\Spyder\Python\lib\site-packages\pandas\core\ops\invalid.py", line 34, in invalid_comparison
raise TypeError(f"Invalid comparison between dtype={left.dtype} and {typ}")

TypeError: Invalid comparison between dtype=datetime64[ns] and date

To confirm, I have pandas version 1.1.5, tensorflow version 2.4.0 and keras version 2.4.3.
* Spyder version: 4.2.1 None
* Python version: 3.7.9 64-bit
* Qt version: 5.12.10
* PyQt5 version: 5.12.3
* Operating System: Windows 10

**Comment by TimRivoli** [comment]
Thank you for bringing this to my attention.  I've uploaded a slightly updated version of Utility.py and PriceTradeAnalyzer.py.  Could you download those into your _classes folder and see if that fixes the problem?  Also, what date format do you use on your computer?  I am probably assuming inputs will be in US date format so there could be an issue there.

**Comment by charifbahloul** [comment]
Thanks. It's now been fixed. Would it be possible to add a short script to pick the best stocks to invest in?

**Comment by TimRivoli** [comment]
Take a look at my https://github.com/TimRivoli/Price-Momentum-Backtesting project.  I've made 55% return in the past year by using TodaysRecommendations(tickerList=tickers, stockCount=100, filterOption=0), which I then sort by largest 1 year return, and filter out a few high deviation picks.  It is essentially taking the top few stocks from the S&P500, by sorting them by highest prior year return and eliminating ones that go up and down a lot.
